[package]
name = "relay_core"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
bincode = { version = "2.0.1" }
chrono = "0.4.40"
ed25519-dalek = { version = "2.1.1", features = ["rand_core"] }
rand = "0.8"
thiserror = "2.0.12"
uuid = { version = "1.16.0", features = ["v4"] }
