# set name of the relay
name = "{relay_name}"

# uncomment below to set initial ttl for created envelopes
# initial_ttl = {default_initial_ttl}

# uncomment below to set max ttl that will be forwarded
# max_forwarding_ttl = {default_max_forwarding_ttl}

# uncomment below to add a relay, duplicate to add more relays
# [[paired_relays]]
# nickname = ""
# key = ""
# # endpoint = ""

# uncomment below to enable listener
# [listener]
# # uncomment below to set listening port
# # port = {default_listening_port}
